// Copyright 2025 IRremoteIDF contributors
//
// Generated by tools/gen_kconfig.py -- do not edit by hand.
//
// Translates the Kconfig (menuconfig) selections into the macros the
// library itself uses. Command line -D flags still win, so an existing
// PlatformIO/Arduino style build recipe keeps working unchanged.

#ifndef IRCONFIG_H_
#define IRCONFIG_H_

#ifndef UNIT_TEST
#include "sdkconfig.h"
#endif  // UNIT_TEST

#ifdef CONFIG_IRREMOTE_KCONFIG_PRESENT

#if defined(CONFIG_IRREMOTE_DEBUG) && !defined(DEBUG)
#define DEBUG 1
#endif

#ifndef _IR_LOCALE_
#ifdef CONFIG_IRREMOTE_LOCALE_DE_CH
#define _IR_LOCALE_ de-CH
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_DE_DE
#define _IR_LOCALE_ de-DE
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_EN_AU
#define _IR_LOCALE_ en-AU
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_EN_IE
#define _IR_LOCALE_ en-IE
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_EN_UK
#define _IR_LOCALE_ en-UK
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_EN_US
#define _IR_LOCALE_ en-US
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_ES_ES
#define _IR_LOCALE_ es-ES
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_FR_FR
#define _IR_LOCALE_ fr-FR
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_IT_IT
#define _IR_LOCALE_ it-IT
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_NL_NL
#define _IR_LOCALE_ nl-NL
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_PT_BR
#define _IR_LOCALE_ pt-BR
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_RU_RU
#define _IR_LOCALE_ ru-RU
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_SK_SK
#define _IR_LOCALE_ sk-SK
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_SV_SE
#define _IR_LOCALE_ sv-SE
#endif
#ifdef CONFIG_IRREMOTE_LOCALE_ZH_CN
#define _IR_LOCALE_ zh-CN
#endif
#endif  // _IR_LOCALE_

#ifndef DECODE_HASH
#ifdef CONFIG_IRREMOTE_DECODE_HASH
#define DECODE_HASH true
#else
#define DECODE_HASH false
#endif
#endif  // DECODE_HASH
#ifndef SEND_RAW
#ifdef CONFIG_IRREMOTE_SEND_RAW
#define SEND_RAW true
#else
#define SEND_RAW false
#endif
#endif  // SEND_RAW
#ifndef DECODE_NEC
#ifdef CONFIG_IRREMOTE_DECODE_NEC
#define DECODE_NEC true
#else
#define DECODE_NEC false
#endif
#endif  // DECODE_NEC
#ifndef SEND_NEC
#ifdef CONFIG_IRREMOTE_SEND_NEC
#define SEND_NEC true
#else
#define SEND_NEC false
#endif
#endif  // SEND_NEC
#ifndef SEND_SHERWOOD
#ifdef CONFIG_IRREMOTE_SEND_SHERWOOD
#define SEND_SHERWOOD true
#else
#define SEND_SHERWOOD false
#endif
#endif  // SEND_SHERWOOD
#ifndef DECODE_RC5
#ifdef CONFIG_IRREMOTE_DECODE_RC5
#define DECODE_RC5 true
#else
#define DECODE_RC5 false
#endif
#endif  // DECODE_RC5
#ifndef SEND_RC5
#ifdef CONFIG_IRREMOTE_SEND_RC5
#define SEND_RC5 true
#else
#define SEND_RC5 false
#endif
#endif  // SEND_RC5
#ifndef DECODE_RC6
#ifdef CONFIG_IRREMOTE_DECODE_RC6
#define DECODE_RC6 true
#else
#define DECODE_RC6 false
#endif
#endif  // DECODE_RC6
#ifndef SEND_RC6
#ifdef CONFIG_IRREMOTE_SEND_RC6
#define SEND_RC6 true
#else
#define SEND_RC6 false
#endif
#endif  // SEND_RC6
#ifndef DECODE_RCMM
#ifdef CONFIG_IRREMOTE_DECODE_RCMM
#define DECODE_RCMM true
#else
#define DECODE_RCMM false
#endif
#endif  // DECODE_RCMM
#ifndef SEND_RCMM
#ifdef CONFIG_IRREMOTE_SEND_RCMM
#define SEND_RCMM true
#else
#define SEND_RCMM false
#endif
#endif  // SEND_RCMM
#ifndef DECODE_SONY
#ifdef CONFIG_IRREMOTE_DECODE_SONY
#define DECODE_SONY true
#else
#define DECODE_SONY false
#endif
#endif  // DECODE_SONY
#ifndef SEND_SONY
#ifdef CONFIG_IRREMOTE_SEND_SONY
#define SEND_SONY true
#else
#define SEND_SONY false
#endif
#endif  // SEND_SONY
#ifndef DECODE_PANASONIC
#ifdef CONFIG_IRREMOTE_DECODE_PANASONIC
#define DECODE_PANASONIC true
#else
#define DECODE_PANASONIC false
#endif
#endif  // DECODE_PANASONIC
#ifndef SEND_PANASONIC
#ifdef CONFIG_IRREMOTE_SEND_PANASONIC
#define SEND_PANASONIC true
#else
#define SEND_PANASONIC false
#endif
#endif  // SEND_PANASONIC
#ifndef DECODE_JVC
#ifdef CONFIG_IRREMOTE_DECODE_JVC
#define DECODE_JVC true
#else
#define DECODE_JVC false
#endif
#endif  // DECODE_JVC
#ifndef SEND_JVC
#ifdef CONFIG_IRREMOTE_SEND_JVC
#define SEND_JVC true
#else
#define SEND_JVC false
#endif
#endif  // SEND_JVC
#ifndef DECODE_SAMSUNG
#ifdef CONFIG_IRREMOTE_DECODE_SAMSUNG
#define DECODE_SAMSUNG true
#else
#define DECODE_SAMSUNG false
#endif
#endif  // DECODE_SAMSUNG
#ifndef SEND_SAMSUNG
#ifdef CONFIG_IRREMOTE_SEND_SAMSUNG
#define SEND_SAMSUNG true
#else
#define SEND_SAMSUNG false
#endif
#endif  // SEND_SAMSUNG
#ifndef DECODE_SAMSUNG36
#ifdef CONFIG_IRREMOTE_DECODE_SAMSUNG36
#define DECODE_SAMSUNG36 true
#else
#define DECODE_SAMSUNG36 false
#endif
#endif  // DECODE_SAMSUNG36
#ifndef SEND_SAMSUNG36
#ifdef CONFIG_IRREMOTE_SEND_SAMSUNG36
#define SEND_SAMSUNG36 true
#else
#define SEND_SAMSUNG36 false
#endif
#endif  // SEND_SAMSUNG36
#ifndef DECODE_SAMSUNG_AC
#ifdef CONFIG_IRREMOTE_DECODE_SAMSUNG_AC
#define DECODE_SAMSUNG_AC true
#else
#define DECODE_SAMSUNG_AC false
#endif
#endif  // DECODE_SAMSUNG_AC
#ifndef SEND_SAMSUNG_AC
#ifdef CONFIG_IRREMOTE_SEND_SAMSUNG_AC
#define SEND_SAMSUNG_AC true
#else
#define SEND_SAMSUNG_AC false
#endif
#endif  // SEND_SAMSUNG_AC
#ifndef DECODE_WHYNTER
#ifdef CONFIG_IRREMOTE_DECODE_WHYNTER
#define DECODE_WHYNTER true
#else
#define DECODE_WHYNTER false
#endif
#endif  // DECODE_WHYNTER
#ifndef SEND_WHYNTER
#ifdef CONFIG_IRREMOTE_SEND_WHYNTER
#define SEND_WHYNTER true
#else
#define SEND_WHYNTER false
#endif
#endif  // SEND_WHYNTER
#ifndef DECODE_AIWA_RC_T501
#ifdef CONFIG_IRREMOTE_DECODE_AIWA_RC_T501
#define DECODE_AIWA_RC_T501 true
#else
#define DECODE_AIWA_RC_T501 false
#endif
#endif  // DECODE_AIWA_RC_T501
#ifndef SEND_AIWA_RC_T501
#ifdef CONFIG_IRREMOTE_SEND_AIWA_RC_T501
#define SEND_AIWA_RC_T501 true
#else
#define SEND_AIWA_RC_T501 false
#endif
#endif  // SEND_AIWA_RC_T501
#ifndef DECODE_LG
#ifdef CONFIG_IRREMOTE_DECODE_LG
#define DECODE_LG true
#else
#define DECODE_LG false
#endif
#endif  // DECODE_LG
#ifndef SEND_LG
#ifdef CONFIG_IRREMOTE_SEND_LG
#define SEND_LG true
#else
#define SEND_LG false
#endif
#endif  // SEND_LG
#ifndef DECODE_SANYO
#ifdef CONFIG_IRREMOTE_DECODE_SANYO
#define DECODE_SANYO true
#else
#define DECODE_SANYO false
#endif
#endif  // DECODE_SANYO
#ifndef SEND_SANYO
#ifdef CONFIG_IRREMOTE_SEND_SANYO
#define SEND_SANYO true
#else
#define SEND_SANYO false
#endif
#endif  // SEND_SANYO
#ifndef DECODE_SANYO_AC
#ifdef CONFIG_IRREMOTE_DECODE_SANYO_AC
#define DECODE_SANYO_AC true
#else
#define DECODE_SANYO_AC false
#endif
#endif  // DECODE_SANYO_AC
#ifndef SEND_SANYO_AC
#ifdef CONFIG_IRREMOTE_SEND_SANYO_AC
#define SEND_SANYO_AC true
#else
#define SEND_SANYO_AC false
#endif
#endif  // SEND_SANYO_AC
#ifndef DECODE_SANYO_AC88
#ifdef CONFIG_IRREMOTE_DECODE_SANYO_AC88
#define DECODE_SANYO_AC88 true
#else
#define DECODE_SANYO_AC88 false
#endif
#endif  // DECODE_SANYO_AC88
#ifndef SEND_SANYO_AC88
#ifdef CONFIG_IRREMOTE_SEND_SANYO_AC88
#define SEND_SANYO_AC88 true
#else
#define SEND_SANYO_AC88 false
#endif
#endif  // SEND_SANYO_AC88
#ifndef DECODE_SANYO_AC152
#ifdef CONFIG_IRREMOTE_DECODE_SANYO_AC152
#define DECODE_SANYO_AC152 true
#else
#define DECODE_SANYO_AC152 false
#endif
#endif  // DECODE_SANYO_AC152
#ifndef SEND_SANYO_AC152
#ifdef CONFIG_IRREMOTE_SEND_SANYO_AC152
#define SEND_SANYO_AC152 true
#else
#define SEND_SANYO_AC152 false
#endif
#endif  // SEND_SANYO_AC152
#ifndef DECODE_MITSUBISHI
#ifdef CONFIG_IRREMOTE_DECODE_MITSUBISHI
#define DECODE_MITSUBISHI true
#else
#define DECODE_MITSUBISHI false
#endif
#endif  // DECODE_MITSUBISHI
#ifndef SEND_MITSUBISHI
#ifdef CONFIG_IRREMOTE_SEND_MITSUBISHI
#define SEND_MITSUBISHI true
#else
#define SEND_MITSUBISHI false
#endif
#endif  // SEND_MITSUBISHI
#ifndef DECODE_MITSUBISHI2
#ifdef CONFIG_IRREMOTE_DECODE_MITSUBISHI2
#define DECODE_MITSUBISHI2 true
#else
#define DECODE_MITSUBISHI2 false
#endif
#endif  // DECODE_MITSUBISHI2
#ifndef SEND_MITSUBISHI2
#ifdef CONFIG_IRREMOTE_SEND_MITSUBISHI2
#define SEND_MITSUBISHI2 true
#else
#define SEND_MITSUBISHI2 false
#endif
#endif  // SEND_MITSUBISHI2
#ifndef DECODE_DISH
#ifdef CONFIG_IRREMOTE_DECODE_DISH
#define DECODE_DISH true
#else
#define DECODE_DISH false
#endif
#endif  // DECODE_DISH
#ifndef SEND_DISH
#ifdef CONFIG_IRREMOTE_SEND_DISH
#define SEND_DISH true
#else
#define SEND_DISH false
#endif
#endif  // SEND_DISH
#ifndef DECODE_SHARP
#ifdef CONFIG_IRREMOTE_DECODE_SHARP
#define DECODE_SHARP true
#else
#define DECODE_SHARP false
#endif
#endif  // DECODE_SHARP
#ifndef SEND_SHARP
#ifdef CONFIG_IRREMOTE_SEND_SHARP
#define SEND_SHARP true
#else
#define SEND_SHARP false
#endif
#endif  // SEND_SHARP
#ifndef DECODE_SHARP_AC
#ifdef CONFIG_IRREMOTE_DECODE_SHARP_AC
#define DECODE_SHARP_AC true
#else
#define DECODE_SHARP_AC false
#endif
#endif  // DECODE_SHARP_AC
#ifndef SEND_SHARP_AC
#ifdef CONFIG_IRREMOTE_SEND_SHARP_AC
#define SEND_SHARP_AC true
#else
#define SEND_SHARP_AC false
#endif
#endif  // SEND_SHARP_AC
#ifndef DECODE_DENON
#ifdef CONFIG_IRREMOTE_DECODE_DENON
#define DECODE_DENON true
#else
#define DECODE_DENON false
#endif
#endif  // DECODE_DENON
#ifndef SEND_DENON
#ifdef CONFIG_IRREMOTE_SEND_DENON
#define SEND_DENON true
#else
#define SEND_DENON false
#endif
#endif  // SEND_DENON
#ifndef DECODE_KELVINATOR
#ifdef CONFIG_IRREMOTE_DECODE_KELVINATOR
#define DECODE_KELVINATOR true
#else
#define DECODE_KELVINATOR false
#endif
#endif  // DECODE_KELVINATOR
#ifndef SEND_KELVINATOR
#ifdef CONFIG_IRREMOTE_SEND_KELVINATOR
#define SEND_KELVINATOR true
#else
#define SEND_KELVINATOR false
#endif
#endif  // SEND_KELVINATOR
#ifndef DECODE_MITSUBISHI_AC
#ifdef CONFIG_IRREMOTE_DECODE_MITSUBISHI_AC
#define DECODE_MITSUBISHI_AC true
#else
#define DECODE_MITSUBISHI_AC false
#endif
#endif  // DECODE_MITSUBISHI_AC
#ifndef SEND_MITSUBISHI_AC
#ifdef CONFIG_IRREMOTE_SEND_MITSUBISHI_AC
#define SEND_MITSUBISHI_AC true
#else
#define SEND_MITSUBISHI_AC false
#endif
#endif  // SEND_MITSUBISHI_AC
#ifndef DECODE_MITSUBISHI136
#ifdef CONFIG_IRREMOTE_DECODE_MITSUBISHI136
#define DECODE_MITSUBISHI136 true
#else
#define DECODE_MITSUBISHI136 false
#endif
#endif  // DECODE_MITSUBISHI136
#ifndef SEND_MITSUBISHI136
#ifdef CONFIG_IRREMOTE_SEND_MITSUBISHI136
#define SEND_MITSUBISHI136 true
#else
#define SEND_MITSUBISHI136 false
#endif
#endif  // SEND_MITSUBISHI136
#ifndef DECODE_MITSUBISHI112
#ifdef CONFIG_IRREMOTE_DECODE_MITSUBISHI112
#define DECODE_MITSUBISHI112 true
#else
#define DECODE_MITSUBISHI112 false
#endif
#endif  // DECODE_MITSUBISHI112
#ifndef SEND_MITSUBISHI112
#ifdef CONFIG_IRREMOTE_SEND_MITSUBISHI112
#define SEND_MITSUBISHI112 true
#else
#define SEND_MITSUBISHI112 false
#endif
#endif  // SEND_MITSUBISHI112
#ifndef DECODE_FUJITSU_AC
#ifdef CONFIG_IRREMOTE_DECODE_FUJITSU_AC
#define DECODE_FUJITSU_AC true
#else
#define DECODE_FUJITSU_AC false
#endif
#endif  // DECODE_FUJITSU_AC
#ifndef SEND_FUJITSU_AC
#ifdef CONFIG_IRREMOTE_SEND_FUJITSU_AC
#define SEND_FUJITSU_AC true
#else
#define SEND_FUJITSU_AC false
#endif
#endif  // SEND_FUJITSU_AC
#ifndef DECODE_INAX
#ifdef CONFIG_IRREMOTE_DECODE_INAX
#define DECODE_INAX true
#else
#define DECODE_INAX false
#endif
#endif  // DECODE_INAX
#ifndef SEND_INAX
#ifdef CONFIG_IRREMOTE_SEND_INAX
#define SEND_INAX true
#else
#define SEND_INAX false
#endif
#endif  // SEND_INAX
#ifndef DECODE_DAIKIN
#ifdef CONFIG_IRREMOTE_DECODE_DAIKIN
#define DECODE_DAIKIN true
#else
#define DECODE_DAIKIN false
#endif
#endif  // DECODE_DAIKIN
#ifndef SEND_DAIKIN
#ifdef CONFIG_IRREMOTE_SEND_DAIKIN
#define SEND_DAIKIN true
#else
#define SEND_DAIKIN false
#endif
#endif  // SEND_DAIKIN
#ifndef DECODE_COOLIX
#ifdef CONFIG_IRREMOTE_DECODE_COOLIX
#define DECODE_COOLIX true
#else
#define DECODE_COOLIX false
#endif
#endif  // DECODE_COOLIX
#ifndef SEND_COOLIX
#ifdef CONFIG_IRREMOTE_SEND_COOLIX
#define SEND_COOLIX true
#else
#define SEND_COOLIX false
#endif
#endif  // SEND_COOLIX
#ifndef DECODE_COOLIX48
#ifdef CONFIG_IRREMOTE_DECODE_COOLIX48
#define DECODE_COOLIX48 true
#else
#define DECODE_COOLIX48 false
#endif
#endif  // DECODE_COOLIX48
#ifndef SEND_COOLIX48
#ifdef CONFIG_IRREMOTE_SEND_COOLIX48
#define SEND_COOLIX48 true
#else
#define SEND_COOLIX48 false
#endif
#endif  // SEND_COOLIX48
#ifndef SEND_GLOBALCACHE
#ifdef CONFIG_IRREMOTE_SEND_GLOBALCACHE
#define SEND_GLOBALCACHE true
#else
#define SEND_GLOBALCACHE false
#endif
#endif  // SEND_GLOBALCACHE
#ifndef DECODE_GOODWEATHER
#ifdef CONFIG_IRREMOTE_DECODE_GOODWEATHER
#define DECODE_GOODWEATHER true
#else
#define DECODE_GOODWEATHER false
#endif
#endif  // DECODE_GOODWEATHER
#ifndef SEND_GOODWEATHER
#ifdef CONFIG_IRREMOTE_SEND_GOODWEATHER
#define SEND_GOODWEATHER true
#else
#define SEND_GOODWEATHER false
#endif
#endif  // SEND_GOODWEATHER
#ifndef DECODE_GREE
#ifdef CONFIG_IRREMOTE_DECODE_GREE
#define DECODE_GREE true
#else
#define DECODE_GREE false
#endif
#endif  // DECODE_GREE
#ifndef SEND_GREE
#ifdef CONFIG_IRREMOTE_SEND_GREE
#define SEND_GREE true
#else
#define SEND_GREE false
#endif
#endif  // SEND_GREE
#ifndef SEND_PRONTO
#ifdef CONFIG_IRREMOTE_SEND_PRONTO
#define SEND_PRONTO true
#else
#define SEND_PRONTO false
#endif
#endif  // SEND_PRONTO
#ifndef DECODE_ARGO
#ifdef CONFIG_IRREMOTE_DECODE_ARGO
#define DECODE_ARGO true
#else
#define DECODE_ARGO false
#endif
#endif  // DECODE_ARGO
#ifndef SEND_ARGO
#ifdef CONFIG_IRREMOTE_SEND_ARGO
#define SEND_ARGO true
#else
#define SEND_ARGO false
#endif
#endif  // SEND_ARGO
#ifndef DECODE_TROTEC
#ifdef CONFIG_IRREMOTE_DECODE_TROTEC
#define DECODE_TROTEC true
#else
#define DECODE_TROTEC false
#endif
#endif  // DECODE_TROTEC
#ifndef SEND_TROTEC
#ifdef CONFIG_IRREMOTE_SEND_TROTEC
#define SEND_TROTEC true
#else
#define SEND_TROTEC false
#endif
#endif  // SEND_TROTEC
#ifndef DECODE_TROTEC_3550
#ifdef CONFIG_IRREMOTE_DECODE_TROTEC_3550
#define DECODE_TROTEC_3550 true
#else
#define DECODE_TROTEC_3550 false
#endif
#endif  // DECODE_TROTEC_3550
#ifndef SEND_TROTEC_3550
#ifdef CONFIG_IRREMOTE_SEND_TROTEC_3550
#define SEND_TROTEC_3550 true
#else
#define SEND_TROTEC_3550 false
#endif
#endif  // SEND_TROTEC_3550
#ifndef DECODE_NIKAI
#ifdef CONFIG_IRREMOTE_DECODE_NIKAI
#define DECODE_NIKAI true
#else
#define DECODE_NIKAI false
#endif
#endif  // DECODE_NIKAI
#ifndef SEND_NIKAI
#ifdef CONFIG_IRREMOTE_SEND_NIKAI
#define SEND_NIKAI true
#else
#define SEND_NIKAI false
#endif
#endif  // SEND_NIKAI
#ifndef DECODE_TOSHIBA_AC
#ifdef CONFIG_IRREMOTE_DECODE_TOSHIBA_AC
#define DECODE_TOSHIBA_AC true
#else
#define DECODE_TOSHIBA_AC false
#endif
#endif  // DECODE_TOSHIBA_AC
#ifndef SEND_TOSHIBA_AC
#ifdef CONFIG_IRREMOTE_SEND_TOSHIBA_AC
#define SEND_TOSHIBA_AC true
#else
#define SEND_TOSHIBA_AC false
#endif
#endif  // SEND_TOSHIBA_AC
#ifndef DECODE_MAGIQUEST
#ifdef CONFIG_IRREMOTE_DECODE_MAGIQUEST
#define DECODE_MAGIQUEST true
#else
#define DECODE_MAGIQUEST false
#endif
#endif  // DECODE_MAGIQUEST
#ifndef SEND_MAGIQUEST
#ifdef CONFIG_IRREMOTE_SEND_MAGIQUEST
#define SEND_MAGIQUEST true
#else
#define SEND_MAGIQUEST false
#endif
#endif  // SEND_MAGIQUEST
#ifndef DECODE_MIDEA
#ifdef CONFIG_IRREMOTE_DECODE_MIDEA
#define DECODE_MIDEA true
#else
#define DECODE_MIDEA false
#endif
#endif  // DECODE_MIDEA
#ifndef SEND_MIDEA
#ifdef CONFIG_IRREMOTE_SEND_MIDEA
#define SEND_MIDEA true
#else
#define SEND_MIDEA false
#endif
#endif  // SEND_MIDEA
#ifndef DECODE_MIDEA24
#ifdef CONFIG_IRREMOTE_DECODE_MIDEA24
#define DECODE_MIDEA24 true
#else
#define DECODE_MIDEA24 false
#endif
#endif  // DECODE_MIDEA24
#ifndef SEND_MIDEA24
#ifdef CONFIG_IRREMOTE_SEND_MIDEA24
#define SEND_MIDEA24 true
#else
#define SEND_MIDEA24 false
#endif
#endif  // SEND_MIDEA24
#ifndef DECODE_LASERTAG
#ifdef CONFIG_IRREMOTE_DECODE_LASERTAG
#define DECODE_LASERTAG true
#else
#define DECODE_LASERTAG false
#endif
#endif  // DECODE_LASERTAG
#ifndef SEND_LASERTAG
#ifdef CONFIG_IRREMOTE_SEND_LASERTAG
#define SEND_LASERTAG true
#else
#define SEND_LASERTAG false
#endif
#endif  // SEND_LASERTAG
#ifndef DECODE_CARRIER_AC
#ifdef CONFIG_IRREMOTE_DECODE_CARRIER_AC
#define DECODE_CARRIER_AC true
#else
#define DECODE_CARRIER_AC false
#endif
#endif  // DECODE_CARRIER_AC
#ifndef SEND_CARRIER_AC
#ifdef CONFIG_IRREMOTE_SEND_CARRIER_AC
#define SEND_CARRIER_AC true
#else
#define SEND_CARRIER_AC false
#endif
#endif  // SEND_CARRIER_AC
#ifndef DECODE_CARRIER_AC40
#ifdef CONFIG_IRREMOTE_DECODE_CARRIER_AC40
#define DECODE_CARRIER_AC40 true
#else
#define DECODE_CARRIER_AC40 false
#endif
#endif  // DECODE_CARRIER_AC40
#ifndef SEND_CARRIER_AC40
#ifdef CONFIG_IRREMOTE_SEND_CARRIER_AC40
#define SEND_CARRIER_AC40 true
#else
#define SEND_CARRIER_AC40 false
#endif
#endif  // SEND_CARRIER_AC40
#ifndef DECODE_CARRIER_AC64
#ifdef CONFIG_IRREMOTE_DECODE_CARRIER_AC64
#define DECODE_CARRIER_AC64 true
#else
#define DECODE_CARRIER_AC64 false
#endif
#endif  // DECODE_CARRIER_AC64
#ifndef SEND_CARRIER_AC64
#ifdef CONFIG_IRREMOTE_SEND_CARRIER_AC64
#define SEND_CARRIER_AC64 true
#else
#define SEND_CARRIER_AC64 false
#endif
#endif  // SEND_CARRIER_AC64
#ifndef DECODE_CARRIER_AC128
#ifdef CONFIG_IRREMOTE_DECODE_CARRIER_AC128
#define DECODE_CARRIER_AC128 true
#else
#define DECODE_CARRIER_AC128 false
#endif
#endif  // DECODE_CARRIER_AC128
#ifndef SEND_CARRIER_AC128
#ifdef CONFIG_IRREMOTE_SEND_CARRIER_AC128
#define SEND_CARRIER_AC128 true
#else
#define SEND_CARRIER_AC128 false
#endif
#endif  // SEND_CARRIER_AC128
#ifndef DECODE_HAIER_AC
#ifdef CONFIG_IRREMOTE_DECODE_HAIER_AC
#define DECODE_HAIER_AC true
#else
#define DECODE_HAIER_AC false
#endif
#endif  // DECODE_HAIER_AC
#ifndef SEND_HAIER_AC
#ifdef CONFIG_IRREMOTE_SEND_HAIER_AC
#define SEND_HAIER_AC true
#else
#define SEND_HAIER_AC false
#endif
#endif  // SEND_HAIER_AC
#ifndef DECODE_HITACHI_AC
#ifdef CONFIG_IRREMOTE_DECODE_HITACHI_AC
#define DECODE_HITACHI_AC true
#else
#define DECODE_HITACHI_AC false
#endif
#endif  // DECODE_HITACHI_AC
#ifndef SEND_HITACHI_AC
#ifdef CONFIG_IRREMOTE_SEND_HITACHI_AC
#define SEND_HITACHI_AC true
#else
#define SEND_HITACHI_AC false
#endif
#endif  // SEND_HITACHI_AC
#ifndef DECODE_HITACHI_AC1
#ifdef CONFIG_IRREMOTE_DECODE_HITACHI_AC1
#define DECODE_HITACHI_AC1 true
#else
#define DECODE_HITACHI_AC1 false
#endif
#endif  // DECODE_HITACHI_AC1
#ifndef SEND_HITACHI_AC1
#ifdef CONFIG_IRREMOTE_SEND_HITACHI_AC1
#define SEND_HITACHI_AC1 true
#else
#define SEND_HITACHI_AC1 false
#endif
#endif  // SEND_HITACHI_AC1
#ifndef DECODE_HITACHI_AC2
#ifdef CONFIG_IRREMOTE_DECODE_HITACHI_AC2
#define DECODE_HITACHI_AC2 true
#else
#define DECODE_HITACHI_AC2 false
#endif
#endif  // DECODE_HITACHI_AC2
#ifndef SEND_HITACHI_AC2
#ifdef CONFIG_IRREMOTE_SEND_HITACHI_AC2
#define SEND_HITACHI_AC2 true
#else
#define SEND_HITACHI_AC2 false
#endif
#endif  // SEND_HITACHI_AC2
#ifndef DECODE_HITACHI_AC3
#ifdef CONFIG_IRREMOTE_DECODE_HITACHI_AC3
#define DECODE_HITACHI_AC3 true
#else
#define DECODE_HITACHI_AC3 false
#endif
#endif  // DECODE_HITACHI_AC3
#ifndef SEND_HITACHI_AC3
#ifdef CONFIG_IRREMOTE_SEND_HITACHI_AC3
#define SEND_HITACHI_AC3 true
#else
#define SEND_HITACHI_AC3 false
#endif
#endif  // SEND_HITACHI_AC3
#ifndef DECODE_HITACHI_AC264
#ifdef CONFIG_IRREMOTE_DECODE_HITACHI_AC264
#define DECODE_HITACHI_AC264 true
#else
#define DECODE_HITACHI_AC264 false
#endif
#endif  // DECODE_HITACHI_AC264
#ifndef SEND_HITACHI_AC264
#ifdef CONFIG_IRREMOTE_SEND_HITACHI_AC264
#define SEND_HITACHI_AC264 true
#else
#define SEND_HITACHI_AC264 false
#endif
#endif  // SEND_HITACHI_AC264
#ifndef DECODE_HITACHI_AC296
#ifdef CONFIG_IRREMOTE_DECODE_HITACHI_AC296
#define DECODE_HITACHI_AC296 true
#else
#define DECODE_HITACHI_AC296 false
#endif
#endif  // DECODE_HITACHI_AC296
#ifndef SEND_HITACHI_AC296
#ifdef CONFIG_IRREMOTE_SEND_HITACHI_AC296
#define SEND_HITACHI_AC296 true
#else
#define SEND_HITACHI_AC296 false
#endif
#endif  // SEND_HITACHI_AC296
#ifndef DECODE_HITACHI_AC344
#ifdef CONFIG_IRREMOTE_DECODE_HITACHI_AC344
#define DECODE_HITACHI_AC344 true
#else
#define DECODE_HITACHI_AC344 false
#endif
#endif  // DECODE_HITACHI_AC344
#ifndef SEND_HITACHI_AC344
#ifdef CONFIG_IRREMOTE_SEND_HITACHI_AC344
#define SEND_HITACHI_AC344 true
#else
#define SEND_HITACHI_AC344 false
#endif
#endif  // SEND_HITACHI_AC344
#ifndef DECODE_HITACHI_AC424
#ifdef CONFIG_IRREMOTE_DECODE_HITACHI_AC424
#define DECODE_HITACHI_AC424 true
#else
#define DECODE_HITACHI_AC424 false
#endif
#endif  // DECODE_HITACHI_AC424
#ifndef SEND_HITACHI_AC424
#ifdef CONFIG_IRREMOTE_SEND_HITACHI_AC424
#define SEND_HITACHI_AC424 true
#else
#define SEND_HITACHI_AC424 false
#endif
#endif  // SEND_HITACHI_AC424
#ifndef DECODE_GICABLE
#ifdef CONFIG_IRREMOTE_DECODE_GICABLE
#define DECODE_GICABLE true
#else
#define DECODE_GICABLE false
#endif
#endif  // DECODE_GICABLE
#ifndef SEND_GICABLE
#ifdef CONFIG_IRREMOTE_SEND_GICABLE
#define SEND_GICABLE true
#else
#define SEND_GICABLE false
#endif
#endif  // SEND_GICABLE
#ifndef DECODE_HAIER_AC_YRW02
#ifdef CONFIG_IRREMOTE_DECODE_HAIER_AC_YRW02
#define DECODE_HAIER_AC_YRW02 true
#else
#define DECODE_HAIER_AC_YRW02 false
#endif
#endif  // DECODE_HAIER_AC_YRW02
#ifndef SEND_HAIER_AC_YRW02
#ifdef CONFIG_IRREMOTE_SEND_HAIER_AC_YRW02
#define SEND_HAIER_AC_YRW02 true
#else
#define SEND_HAIER_AC_YRW02 false
#endif
#endif  // SEND_HAIER_AC_YRW02
#ifndef DECODE_WHIRLPOOL_AC
#ifdef CONFIG_IRREMOTE_DECODE_WHIRLPOOL_AC
#define DECODE_WHIRLPOOL_AC true
#else
#define DECODE_WHIRLPOOL_AC false
#endif
#endif  // DECODE_WHIRLPOOL_AC
#ifndef SEND_WHIRLPOOL_AC
#ifdef CONFIG_IRREMOTE_SEND_WHIRLPOOL_AC
#define SEND_WHIRLPOOL_AC true
#else
#define SEND_WHIRLPOOL_AC false
#endif
#endif  // SEND_WHIRLPOOL_AC
#ifndef DECODE_LUTRON
#ifdef CONFIG_IRREMOTE_DECODE_LUTRON
#define DECODE_LUTRON true
#else
#define DECODE_LUTRON false
#endif
#endif  // DECODE_LUTRON
#ifndef SEND_LUTRON
#ifdef CONFIG_IRREMOTE_SEND_LUTRON
#define SEND_LUTRON true
#else
#define SEND_LUTRON false
#endif
#endif  // SEND_LUTRON
#ifndef DECODE_ELECTRA_AC
#ifdef CONFIG_IRREMOTE_DECODE_ELECTRA_AC
#define DECODE_ELECTRA_AC true
#else
#define DECODE_ELECTRA_AC false
#endif
#endif  // DECODE_ELECTRA_AC
#ifndef SEND_ELECTRA_AC
#ifdef CONFIG_IRREMOTE_SEND_ELECTRA_AC
#define SEND_ELECTRA_AC true
#else
#define SEND_ELECTRA_AC false
#endif
#endif  // SEND_ELECTRA_AC
#ifndef DECODE_PANASONIC_AC
#ifdef CONFIG_IRREMOTE_DECODE_PANASONIC_AC
#define DECODE_PANASONIC_AC true
#else
#define DECODE_PANASONIC_AC false
#endif
#endif  // DECODE_PANASONIC_AC
#ifndef SEND_PANASONIC_AC
#ifdef CONFIG_IRREMOTE_SEND_PANASONIC_AC
#define SEND_PANASONIC_AC true
#else
#define SEND_PANASONIC_AC false
#endif
#endif  // SEND_PANASONIC_AC
#ifndef DECODE_PANASONIC_AC32
#ifdef CONFIG_IRREMOTE_DECODE_PANASONIC_AC32
#define DECODE_PANASONIC_AC32 true
#else
#define DECODE_PANASONIC_AC32 false
#endif
#endif  // DECODE_PANASONIC_AC32
#ifndef SEND_PANASONIC_AC32
#ifdef CONFIG_IRREMOTE_SEND_PANASONIC_AC32
#define SEND_PANASONIC_AC32 true
#else
#define SEND_PANASONIC_AC32 false
#endif
#endif  // SEND_PANASONIC_AC32
#ifndef DECODE_MWM
#ifdef CONFIG_IRREMOTE_DECODE_MWM
#define DECODE_MWM true
#else
#define DECODE_MWM false
#endif
#endif  // DECODE_MWM
#ifndef SEND_MWM
#ifdef CONFIG_IRREMOTE_SEND_MWM
#define SEND_MWM true
#else
#define SEND_MWM false
#endif
#endif  // SEND_MWM
#ifndef DECODE_PIONEER
#ifdef CONFIG_IRREMOTE_DECODE_PIONEER
#define DECODE_PIONEER true
#else
#define DECODE_PIONEER false
#endif
#endif  // DECODE_PIONEER
#ifndef SEND_PIONEER
#ifdef CONFIG_IRREMOTE_SEND_PIONEER
#define SEND_PIONEER true
#else
#define SEND_PIONEER false
#endif
#endif  // SEND_PIONEER
#ifndef DECODE_DAIKIN2
#ifdef CONFIG_IRREMOTE_DECODE_DAIKIN2
#define DECODE_DAIKIN2 true
#else
#define DECODE_DAIKIN2 false
#endif
#endif  // DECODE_DAIKIN2
#ifndef SEND_DAIKIN2
#ifdef CONFIG_IRREMOTE_SEND_DAIKIN2
#define SEND_DAIKIN2 true
#else
#define SEND_DAIKIN2 false
#endif
#endif  // SEND_DAIKIN2
#ifndef DECODE_VESTEL_AC
#ifdef CONFIG_IRREMOTE_DECODE_VESTEL_AC
#define DECODE_VESTEL_AC true
#else
#define DECODE_VESTEL_AC false
#endif
#endif  // DECODE_VESTEL_AC
#ifndef SEND_VESTEL_AC
#ifdef CONFIG_IRREMOTE_SEND_VESTEL_AC
#define SEND_VESTEL_AC true
#else
#define SEND_VESTEL_AC false
#endif
#endif  // SEND_VESTEL_AC
#ifndef DECODE_TECO
#ifdef CONFIG_IRREMOTE_DECODE_TECO
#define DECODE_TECO true
#else
#define DECODE_TECO false
#endif
#endif  // DECODE_TECO
#ifndef SEND_TECO
#ifdef CONFIG_IRREMOTE_SEND_TECO
#define SEND_TECO true
#else
#define SEND_TECO false
#endif
#endif  // SEND_TECO
#ifndef DECODE_TCL96AC
#ifdef CONFIG_IRREMOTE_DECODE_TCL96AC
#define DECODE_TCL96AC true
#else
#define DECODE_TCL96AC false
#endif
#endif  // DECODE_TCL96AC
#ifndef SEND_TCL96AC
#ifdef CONFIG_IRREMOTE_SEND_TCL96AC
#define SEND_TCL96AC true
#else
#define SEND_TCL96AC false
#endif
#endif  // SEND_TCL96AC
#ifndef DECODE_TCL112AC
#ifdef CONFIG_IRREMOTE_DECODE_TCL112AC
#define DECODE_TCL112AC true
#else
#define DECODE_TCL112AC false
#endif
#endif  // DECODE_TCL112AC
#ifndef SEND_TCL112AC
#ifdef CONFIG_IRREMOTE_SEND_TCL112AC
#define SEND_TCL112AC true
#else
#define SEND_TCL112AC false
#endif
#endif  // SEND_TCL112AC
#ifndef DECODE_LEGOPF
#ifdef CONFIG_IRREMOTE_DECODE_LEGOPF
#define DECODE_LEGOPF true
#else
#define DECODE_LEGOPF false
#endif
#endif  // DECODE_LEGOPF
#ifndef SEND_LEGOPF
#ifdef CONFIG_IRREMOTE_SEND_LEGOPF
#define SEND_LEGOPF true
#else
#define SEND_LEGOPF false
#endif
#endif  // SEND_LEGOPF
#ifndef DECODE_MITSUBISHIHEAVY
#ifdef CONFIG_IRREMOTE_DECODE_MITSUBISHIHEAVY
#define DECODE_MITSUBISHIHEAVY true
#else
#define DECODE_MITSUBISHIHEAVY false
#endif
#endif  // DECODE_MITSUBISHIHEAVY
#ifndef SEND_MITSUBISHIHEAVY
#ifdef CONFIG_IRREMOTE_SEND_MITSUBISHIHEAVY
#define SEND_MITSUBISHIHEAVY true
#else
#define SEND_MITSUBISHIHEAVY false
#endif
#endif  // SEND_MITSUBISHIHEAVY
#ifndef DECODE_DAIKIN216
#ifdef CONFIG_IRREMOTE_DECODE_DAIKIN216
#define DECODE_DAIKIN216 true
#else
#define DECODE_DAIKIN216 false
#endif
#endif  // DECODE_DAIKIN216
#ifndef SEND_DAIKIN216
#ifdef CONFIG_IRREMOTE_SEND_DAIKIN216
#define SEND_DAIKIN216 true
#else
#define SEND_DAIKIN216 false
#endif
#endif  // SEND_DAIKIN216
#ifndef DECODE_DAIKIN160
#ifdef CONFIG_IRREMOTE_DECODE_DAIKIN160
#define DECODE_DAIKIN160 true
#else
#define DECODE_DAIKIN160 false
#endif
#endif  // DECODE_DAIKIN160
#ifndef SEND_DAIKIN160
#ifdef CONFIG_IRREMOTE_SEND_DAIKIN160
#define SEND_DAIKIN160 true
#else
#define SEND_DAIKIN160 false
#endif
#endif  // SEND_DAIKIN160
#ifndef DECODE_NEOCLIMA
#ifdef CONFIG_IRREMOTE_DECODE_NEOCLIMA
#define DECODE_NEOCLIMA true
#else
#define DECODE_NEOCLIMA false
#endif
#endif  // DECODE_NEOCLIMA
#ifndef SEND_NEOCLIMA
#ifdef CONFIG_IRREMOTE_SEND_NEOCLIMA
#define SEND_NEOCLIMA true
#else
#define SEND_NEOCLIMA false
#endif
#endif  // SEND_NEOCLIMA
#ifndef DECODE_DAIKIN176
#ifdef CONFIG_IRREMOTE_DECODE_DAIKIN176
#define DECODE_DAIKIN176 true
#else
#define DECODE_DAIKIN176 false
#endif
#endif  // DECODE_DAIKIN176
#ifndef SEND_DAIKIN176
#ifdef CONFIG_IRREMOTE_SEND_DAIKIN176
#define SEND_DAIKIN176 true
#else
#define SEND_DAIKIN176 false
#endif
#endif  // SEND_DAIKIN176
#ifndef DECODE_DAIKIN128
#ifdef CONFIG_IRREMOTE_DECODE_DAIKIN128
#define DECODE_DAIKIN128 true
#else
#define DECODE_DAIKIN128 false
#endif
#endif  // DECODE_DAIKIN128
#ifndef SEND_DAIKIN128
#ifdef CONFIG_IRREMOTE_SEND_DAIKIN128
#define SEND_DAIKIN128 true
#else
#define SEND_DAIKIN128 false
#endif
#endif  // SEND_DAIKIN128
#ifndef DECODE_AMCOR
#ifdef CONFIG_IRREMOTE_DECODE_AMCOR
#define DECODE_AMCOR true
#else
#define DECODE_AMCOR false
#endif
#endif  // DECODE_AMCOR
#ifndef SEND_AMCOR
#ifdef CONFIG_IRREMOTE_SEND_AMCOR
#define SEND_AMCOR true
#else
#define SEND_AMCOR false
#endif
#endif  // SEND_AMCOR
#ifndef DECODE_DAIKIN152
#ifdef CONFIG_IRREMOTE_DECODE_DAIKIN152
#define DECODE_DAIKIN152 true
#else
#define DECODE_DAIKIN152 false
#endif
#endif  // DECODE_DAIKIN152
#ifndef SEND_DAIKIN152
#ifdef CONFIG_IRREMOTE_SEND_DAIKIN152
#define SEND_DAIKIN152 true
#else
#define SEND_DAIKIN152 false
#endif
#endif  // SEND_DAIKIN152
#ifndef DECODE_EPSON
#ifdef CONFIG_IRREMOTE_DECODE_EPSON
#define DECODE_EPSON true
#else
#define DECODE_EPSON false
#endif
#endif  // DECODE_EPSON
#ifndef SEND_EPSON
#ifdef CONFIG_IRREMOTE_SEND_EPSON
#define SEND_EPSON true
#else
#define SEND_EPSON false
#endif
#endif  // SEND_EPSON
#ifndef DECODE_SYMPHONY
#ifdef CONFIG_IRREMOTE_DECODE_SYMPHONY
#define DECODE_SYMPHONY true
#else
#define DECODE_SYMPHONY false
#endif
#endif  // DECODE_SYMPHONY
#ifndef SEND_SYMPHONY
#ifdef CONFIG_IRREMOTE_SEND_SYMPHONY
#define SEND_SYMPHONY true
#else
#define SEND_SYMPHONY false
#endif
#endif  // SEND_SYMPHONY
#ifndef DECODE_DAIKIN64
#ifdef CONFIG_IRREMOTE_DECODE_DAIKIN64
#define DECODE_DAIKIN64 true
#else
#define DECODE_DAIKIN64 false
#endif
#endif  // DECODE_DAIKIN64
#ifndef SEND_DAIKIN64
#ifdef CONFIG_IRREMOTE_SEND_DAIKIN64
#define SEND_DAIKIN64 true
#else
#define SEND_DAIKIN64 false
#endif
#endif  // SEND_DAIKIN64
#ifndef DECODE_AIRWELL
#ifdef CONFIG_IRREMOTE_DECODE_AIRWELL
#define DECODE_AIRWELL true
#else
#define DECODE_AIRWELL false
#endif
#endif  // DECODE_AIRWELL
#ifndef SEND_AIRWELL
#ifdef CONFIG_IRREMOTE_SEND_AIRWELL
#define SEND_AIRWELL true
#else
#define SEND_AIRWELL false
#endif
#endif  // SEND_AIRWELL
#ifndef DECODE_DELONGHI_AC
#ifdef CONFIG_IRREMOTE_DECODE_DELONGHI_AC
#define DECODE_DELONGHI_AC true
#else
#define DECODE_DELONGHI_AC false
#endif
#endif  // DECODE_DELONGHI_AC
#ifndef SEND_DELONGHI_AC
#ifdef CONFIG_IRREMOTE_SEND_DELONGHI_AC
#define SEND_DELONGHI_AC true
#else
#define SEND_DELONGHI_AC false
#endif
#endif  // SEND_DELONGHI_AC
#ifndef DECODE_DOSHISHA
#ifdef CONFIG_IRREMOTE_DECODE_DOSHISHA
#define DECODE_DOSHISHA true
#else
#define DECODE_DOSHISHA false
#endif
#endif  // DECODE_DOSHISHA
#ifndef SEND_DOSHISHA
#ifdef CONFIG_IRREMOTE_SEND_DOSHISHA
#define SEND_DOSHISHA true
#else
#define SEND_DOSHISHA false
#endif
#endif  // SEND_DOSHISHA
#ifndef DECODE_MULTIBRACKETS
#ifdef CONFIG_IRREMOTE_DECODE_MULTIBRACKETS
#define DECODE_MULTIBRACKETS true
#else
#define DECODE_MULTIBRACKETS false
#endif
#endif  // DECODE_MULTIBRACKETS
#ifndef SEND_MULTIBRACKETS
#ifdef CONFIG_IRREMOTE_SEND_MULTIBRACKETS
#define SEND_MULTIBRACKETS true
#else
#define SEND_MULTIBRACKETS false
#endif
#endif  // SEND_MULTIBRACKETS
#ifndef DECODE_TECHNIBEL_AC
#ifdef CONFIG_IRREMOTE_DECODE_TECHNIBEL_AC
#define DECODE_TECHNIBEL_AC true
#else
#define DECODE_TECHNIBEL_AC false
#endif
#endif  // DECODE_TECHNIBEL_AC
#ifndef SEND_TECHNIBEL_AC
#ifdef CONFIG_IRREMOTE_SEND_TECHNIBEL_AC
#define SEND_TECHNIBEL_AC true
#else
#define SEND_TECHNIBEL_AC false
#endif
#endif  // SEND_TECHNIBEL_AC
#ifndef DECODE_CORONA_AC
#ifdef CONFIG_IRREMOTE_DECODE_CORONA_AC
#define DECODE_CORONA_AC true
#else
#define DECODE_CORONA_AC false
#endif
#endif  // DECODE_CORONA_AC
#ifndef SEND_CORONA_AC
#ifdef CONFIG_IRREMOTE_SEND_CORONA_AC
#define SEND_CORONA_AC true
#else
#define SEND_CORONA_AC false
#endif
#endif  // SEND_CORONA_AC
#ifndef DECODE_ZEPEAL
#ifdef CONFIG_IRREMOTE_DECODE_ZEPEAL
#define DECODE_ZEPEAL true
#else
#define DECODE_ZEPEAL false
#endif
#endif  // DECODE_ZEPEAL
#ifndef SEND_ZEPEAL
#ifdef CONFIG_IRREMOTE_SEND_ZEPEAL
#define SEND_ZEPEAL true
#else
#define SEND_ZEPEAL false
#endif
#endif  // SEND_ZEPEAL
#ifndef DECODE_VOLTAS
#ifdef CONFIG_IRREMOTE_DECODE_VOLTAS
#define DECODE_VOLTAS true
#else
#define DECODE_VOLTAS false
#endif
#endif  // DECODE_VOLTAS
#ifndef SEND_VOLTAS
#ifdef CONFIG_IRREMOTE_SEND_VOLTAS
#define SEND_VOLTAS true
#else
#define SEND_VOLTAS false
#endif
#endif  // SEND_VOLTAS
#ifndef DECODE_METZ
#ifdef CONFIG_IRREMOTE_DECODE_METZ
#define DECODE_METZ true
#else
#define DECODE_METZ false
#endif
#endif  // DECODE_METZ
#ifndef SEND_METZ
#ifdef CONFIG_IRREMOTE_SEND_METZ
#define SEND_METZ true
#else
#define SEND_METZ false
#endif
#endif  // SEND_METZ
#ifndef DECODE_TRANSCOLD
#ifdef CONFIG_IRREMOTE_DECODE_TRANSCOLD
#define DECODE_TRANSCOLD true
#else
#define DECODE_TRANSCOLD false
#endif
#endif  // DECODE_TRANSCOLD
#ifndef SEND_TRANSCOLD
#ifdef CONFIG_IRREMOTE_SEND_TRANSCOLD
#define SEND_TRANSCOLD true
#else
#define SEND_TRANSCOLD false
#endif
#endif  // SEND_TRANSCOLD
#ifndef DECODE_MIRAGE
#ifdef CONFIG_IRREMOTE_DECODE_MIRAGE
#define DECODE_MIRAGE true
#else
#define DECODE_MIRAGE false
#endif
#endif  // DECODE_MIRAGE
#ifndef SEND_MIRAGE
#ifdef CONFIG_IRREMOTE_SEND_MIRAGE
#define SEND_MIRAGE true
#else
#define SEND_MIRAGE false
#endif
#endif  // SEND_MIRAGE
#ifndef DECODE_ELITESCREENS
#ifdef CONFIG_IRREMOTE_DECODE_ELITESCREENS
#define DECODE_ELITESCREENS true
#else
#define DECODE_ELITESCREENS false
#endif
#endif  // DECODE_ELITESCREENS
#ifndef SEND_ELITESCREENS
#ifdef CONFIG_IRREMOTE_SEND_ELITESCREENS
#define SEND_ELITESCREENS true
#else
#define SEND_ELITESCREENS false
#endif
#endif  // SEND_ELITESCREENS
#ifndef DECODE_MILESTAG2
#ifdef CONFIG_IRREMOTE_DECODE_MILESTAG2
#define DECODE_MILESTAG2 true
#else
#define DECODE_MILESTAG2 false
#endif
#endif  // DECODE_MILESTAG2
#ifndef SEND_MILESTAG2
#ifdef CONFIG_IRREMOTE_SEND_MILESTAG2
#define SEND_MILESTAG2 true
#else
#define SEND_MILESTAG2 false
#endif
#endif  // SEND_MILESTAG2
#ifndef DECODE_ECOCLIM
#ifdef CONFIG_IRREMOTE_DECODE_ECOCLIM
#define DECODE_ECOCLIM true
#else
#define DECODE_ECOCLIM false
#endif
#endif  // DECODE_ECOCLIM
#ifndef SEND_ECOCLIM
#ifdef CONFIG_IRREMOTE_SEND_ECOCLIM
#define SEND_ECOCLIM true
#else
#define SEND_ECOCLIM false
#endif
#endif  // SEND_ECOCLIM
#ifndef DECODE_XMP
#ifdef CONFIG_IRREMOTE_DECODE_XMP
#define DECODE_XMP true
#else
#define DECODE_XMP false
#endif
#endif  // DECODE_XMP
#ifndef SEND_XMP
#ifdef CONFIG_IRREMOTE_SEND_XMP
#define SEND_XMP true
#else
#define SEND_XMP false
#endif
#endif  // SEND_XMP
#ifndef DECODE_TRUMA
#ifdef CONFIG_IRREMOTE_DECODE_TRUMA
#define DECODE_TRUMA true
#else
#define DECODE_TRUMA false
#endif
#endif  // DECODE_TRUMA
#ifndef SEND_TRUMA
#ifdef CONFIG_IRREMOTE_SEND_TRUMA
#define SEND_TRUMA true
#else
#define SEND_TRUMA false
#endif
#endif  // SEND_TRUMA
#ifndef DECODE_HAIER_AC176
#ifdef CONFIG_IRREMOTE_DECODE_HAIER_AC176
#define DECODE_HAIER_AC176 true
#else
#define DECODE_HAIER_AC176 false
#endif
#endif  // DECODE_HAIER_AC176
#ifndef SEND_HAIER_AC176
#ifdef CONFIG_IRREMOTE_SEND_HAIER_AC176
#define SEND_HAIER_AC176 true
#else
#define SEND_HAIER_AC176 false
#endif
#endif  // SEND_HAIER_AC176
#ifndef DECODE_TEKNOPOINT
#ifdef CONFIG_IRREMOTE_DECODE_TEKNOPOINT
#define DECODE_TEKNOPOINT true
#else
#define DECODE_TEKNOPOINT false
#endif
#endif  // DECODE_TEKNOPOINT
#ifndef SEND_TEKNOPOINT
#ifdef CONFIG_IRREMOTE_SEND_TEKNOPOINT
#define SEND_TEKNOPOINT true
#else
#define SEND_TEKNOPOINT false
#endif
#endif  // SEND_TEKNOPOINT
#ifndef DECODE_KELON
#ifdef CONFIG_IRREMOTE_DECODE_KELON
#define DECODE_KELON true
#else
#define DECODE_KELON false
#endif
#endif  // DECODE_KELON
#ifndef SEND_KELON
#ifdef CONFIG_IRREMOTE_SEND_KELON
#define SEND_KELON true
#else
#define SEND_KELON false
#endif
#endif  // SEND_KELON
#ifndef DECODE_BOSE
#ifdef CONFIG_IRREMOTE_DECODE_BOSE
#define DECODE_BOSE true
#else
#define DECODE_BOSE false
#endif
#endif  // DECODE_BOSE
#ifndef SEND_BOSE
#ifdef CONFIG_IRREMOTE_SEND_BOSE
#define SEND_BOSE true
#else
#define SEND_BOSE false
#endif
#endif  // SEND_BOSE
#ifndef DECODE_ARRIS
#ifdef CONFIG_IRREMOTE_DECODE_ARRIS
#define DECODE_ARRIS true
#else
#define DECODE_ARRIS false
#endif
#endif  // DECODE_ARRIS
#ifndef SEND_ARRIS
#ifdef CONFIG_IRREMOTE_SEND_ARRIS
#define SEND_ARRIS true
#else
#define SEND_ARRIS false
#endif
#endif  // SEND_ARRIS
#ifndef DECODE_RHOSS
#ifdef CONFIG_IRREMOTE_DECODE_RHOSS
#define DECODE_RHOSS true
#else
#define DECODE_RHOSS false
#endif
#endif  // DECODE_RHOSS
#ifndef SEND_RHOSS
#ifdef CONFIG_IRREMOTE_SEND_RHOSS
#define SEND_RHOSS true
#else
#define SEND_RHOSS false
#endif
#endif  // SEND_RHOSS
#ifndef DECODE_AIRTON
#ifdef CONFIG_IRREMOTE_DECODE_AIRTON
#define DECODE_AIRTON true
#else
#define DECODE_AIRTON false
#endif
#endif  // DECODE_AIRTON
#ifndef SEND_AIRTON
#ifdef CONFIG_IRREMOTE_SEND_AIRTON
#define SEND_AIRTON true
#else
#define SEND_AIRTON false
#endif
#endif  // SEND_AIRTON
#ifndef DECODE_KELON168
#ifdef CONFIG_IRREMOTE_DECODE_KELON168
#define DECODE_KELON168 true
#else
#define DECODE_KELON168 false
#endif
#endif  // DECODE_KELON168
#ifndef SEND_KELON168
#ifdef CONFIG_IRREMOTE_SEND_KELON168
#define SEND_KELON168 true
#else
#define SEND_KELON168 false
#endif
#endif  // SEND_KELON168
#ifndef DECODE_DAIKIN200
#ifdef CONFIG_IRREMOTE_DECODE_DAIKIN200
#define DECODE_DAIKIN200 true
#else
#define DECODE_DAIKIN200 false
#endif
#endif  // DECODE_DAIKIN200
#ifndef SEND_DAIKIN200
#ifdef CONFIG_IRREMOTE_SEND_DAIKIN200
#define SEND_DAIKIN200 true
#else
#define SEND_DAIKIN200 false
#endif
#endif  // SEND_DAIKIN200
#ifndef DECODE_HAIER_AC160
#ifdef CONFIG_IRREMOTE_DECODE_HAIER_AC160
#define DECODE_HAIER_AC160 true
#else
#define DECODE_HAIER_AC160 false
#endif
#endif  // DECODE_HAIER_AC160
#ifndef SEND_HAIER_AC160
#ifdef CONFIG_IRREMOTE_SEND_HAIER_AC160
#define SEND_HAIER_AC160 true
#else
#define SEND_HAIER_AC160 false
#endif
#endif  // SEND_HAIER_AC160
#ifndef DECODE_TOTO
#ifdef CONFIG_IRREMOTE_DECODE_TOTO
#define DECODE_TOTO true
#else
#define DECODE_TOTO false
#endif
#endif  // DECODE_TOTO
#ifndef SEND_TOTO
#ifdef CONFIG_IRREMOTE_SEND_TOTO
#define SEND_TOTO true
#else
#define SEND_TOTO false
#endif
#endif  // SEND_TOTO
#ifndef DECODE_CLIMABUTLER
#ifdef CONFIG_IRREMOTE_DECODE_CLIMABUTLER
#define DECODE_CLIMABUTLER true
#else
#define DECODE_CLIMABUTLER false
#endif
#endif  // DECODE_CLIMABUTLER
#ifndef SEND_CLIMABUTLER
#ifdef CONFIG_IRREMOTE_SEND_CLIMABUTLER
#define SEND_CLIMABUTLER true
#else
#define SEND_CLIMABUTLER false
#endif
#endif  // SEND_CLIMABUTLER
#ifndef DECODE_BOSCH144
#ifdef CONFIG_IRREMOTE_DECODE_BOSCH144
#define DECODE_BOSCH144 true
#else
#define DECODE_BOSCH144 false
#endif
#endif  // DECODE_BOSCH144
#ifndef SEND_BOSCH144
#ifdef CONFIG_IRREMOTE_SEND_BOSCH144
#define SEND_BOSCH144 true
#else
#define SEND_BOSCH144 false
#endif
#endif  // SEND_BOSCH144
#ifndef DECODE_DAIKIN312
#ifdef CONFIG_IRREMOTE_DECODE_DAIKIN312
#define DECODE_DAIKIN312 true
#else
#define DECODE_DAIKIN312 false
#endif
#endif  // DECODE_DAIKIN312
#ifndef SEND_DAIKIN312
#ifdef CONFIG_IRREMOTE_SEND_DAIKIN312
#define SEND_DAIKIN312 true
#else
#define SEND_DAIKIN312 false
#endif
#endif  // SEND_DAIKIN312
#ifndef DECODE_GORENJE
#ifdef CONFIG_IRREMOTE_DECODE_GORENJE
#define DECODE_GORENJE true
#else
#define DECODE_GORENJE false
#endif
#endif  // DECODE_GORENJE
#ifndef SEND_GORENJE
#ifdef CONFIG_IRREMOTE_SEND_GORENJE
#define SEND_GORENJE true
#else
#define SEND_GORENJE false
#endif
#endif  // SEND_GORENJE
#ifndef DECODE_WOWWEE
#ifdef CONFIG_IRREMOTE_DECODE_WOWWEE
#define DECODE_WOWWEE true
#else
#define DECODE_WOWWEE false
#endif
#endif  // DECODE_WOWWEE
#ifndef SEND_WOWWEE
#ifdef CONFIG_IRREMOTE_SEND_WOWWEE
#define SEND_WOWWEE true
#else
#define SEND_WOWWEE false
#endif
#endif  // SEND_WOWWEE
#ifndef DECODE_CARRIER_AC84
#ifdef CONFIG_IRREMOTE_DECODE_CARRIER_AC84
#define DECODE_CARRIER_AC84 true
#else
#define DECODE_CARRIER_AC84 false
#endif
#endif  // DECODE_CARRIER_AC84
#ifndef SEND_CARRIER_AC84
#ifdef CONFIG_IRREMOTE_SEND_CARRIER_AC84
#define SEND_CARRIER_AC84 true
#else
#define SEND_CARRIER_AC84 false
#endif
#endif  // SEND_CARRIER_AC84
#ifndef DECODE_YORK
#ifdef CONFIG_IRREMOTE_DECODE_YORK
#define DECODE_YORK true
#else
#define DECODE_YORK false
#endif
#endif  // DECODE_YORK
#ifndef SEND_YORK
#ifdef CONFIG_IRREMOTE_SEND_YORK
#define SEND_YORK true
#else
#define SEND_YORK false
#endif
#endif  // SEND_YORK
#ifndef DECODE_BLUESTARHEAVY
#ifdef CONFIG_IRREMOTE_DECODE_BLUESTARHEAVY
#define DECODE_BLUESTARHEAVY true
#else
#define DECODE_BLUESTARHEAVY false
#endif
#endif  // DECODE_BLUESTARHEAVY
#ifndef SEND_BLUESTARHEAVY
#ifdef CONFIG_IRREMOTE_SEND_BLUESTARHEAVY
#define SEND_BLUESTARHEAVY true
#else
#define SEND_BLUESTARHEAVY false
#endif
#endif  // SEND_BLUESTARHEAVY
#ifndef DECODE_EUROM
#ifdef CONFIG_IRREMOTE_DECODE_EUROM
#define DECODE_EUROM true
#else
#define DECODE_EUROM false
#endif
#endif  // DECODE_EUROM
#ifndef SEND_EUROM
#ifdef CONFIG_IRREMOTE_SEND_EUROM
#define SEND_EUROM true
#else
#define SEND_EUROM false
#endif
#endif  // SEND_EUROM

#endif  // CONFIG_IRREMOTE_KCONFIG_PRESENT

#endif  // IRCONFIG_H_
