#!/usr/bin/env python3
"""Generate Kconfig and include/IRconfig.h from the protocol list.

The protocol toggles live in include/IRremoteESP8266.h as `#ifndef X /
#define X _IR_ENABLE_DEFAULT_ / #endif` triples. This script mirrors each of
them as a Kconfig symbol so users can trim unused protocols with `idf.py
menuconfig` instead of hand-written -D flags.

Run from the repository root:  python3 tools/gen_kconfig.py
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(ROOT, "include", "IRremoteESP8266.h")
LOCALE_DIR = os.path.join(ROOT, "include", "locale")
KCONFIG = os.path.join(ROOT, "Kconfig")
CONFIG_H = os.path.join(ROOT, "include", "IRconfig.h")

TOGGLE_RE = re.compile(
    r"^#define\s+((?:DECODE|SEND)_[A-Z0-9_]+)\s+_IR_ENABLE_DEFAULT_\s*$",
    re.MULTILINE)


def collect_toggles():
    """Return the protocol toggle macros, in source order."""
    with open(HEADER) as f:
        names = TOGGLE_RE.findall(f.read())
    seen = set()
    ordered = []
    for name in names:
        if name not in seen:
            seen.add(name)
            ordered.append(name)
    return ordered


def collect_locales():
    """Return the available locale tags, e.g. ['en-AU', 'es-ES', ...]."""
    tags = [f[:-2] for f in os.listdir(LOCALE_DIR)
            if f.endswith(".h") and f != "defaults.h"]
    return sorted(tags)


def protocol_of(toggle):
    return toggle.split("_", 1)[1]


def write_kconfig(toggles, locales):
    out = []
    w = out.append
    w("# Generated by tools/gen_kconfig.py -- do not edit by hand.")
    w("")
    w('menu "IRremote (infrared send/receive)"')
    w("")
    w("config IRREMOTE_KCONFIG_PRESENT")
    w("    bool")
    w("    default y")
    w("    help")
    w("        Internal marker so the library knows the Kconfig options")
    w("        were applied. Not user selectable.")
    w("")
    w("config IRREMOTE_TX_HW_CARRIER")
    w('    bool "Generate the transmit carrier in hardware (LEDC)"')
    w("    default n")
    w("    help")
    w("        Use an LEDC channel to produce the 30-60 kHz carrier instead of")
    w("        toggling the GPIO from the CPU. This frees the CPU during a")
    w("        transmission and gives a cleaner duty cycle, at the cost of one")
    w("        LEDC channel and timer per IRsend instance.")
    w("")
    w("config IRREMOTE_DEBUG")
    w('    bool "Print library debug output"')
    w("    default n")
    w("    help")
    w("        Enables the library's DPRINT/DPRINTLN tracing on stdout.")
    w("")
    w("choice IRREMOTE_LOCALE")
    w('    prompt "Language/locale for human readable output"')
    w("    default IRREMOTE_LOCALE_EN_AU")
    w("    help")
    w("        Selects which include/locale/<tag>.h file supplies the text")
    w("        used by toString() and friends.")
    w("")
    for tag in locales:
        w("config IRREMOTE_LOCALE_%s" % tag.upper().replace("-", "_"))
        w('    bool "%s"' % tag)
    w("")
    w("endchoice")
    w("")
    w("config IRREMOTE_ENABLE_ALL_PROTOCOLS")
    w('    bool "Enable every supported protocol"')
    w("    default y")
    w("    help")
    w("        Every protocol is compiled in. Turn this off to pick protocols")
    w("        individually and shrink the firmware.")
    w("")
    w('menu "Protocols"')
    w("    visible if !IRREMOTE_ENABLE_ALL_PROTOCOLS")
    w("")
    for toggle in toggles:
        kind = "decode" if toggle.startswith("DECODE_") else "send"
        w("config IRREMOTE_%s" % toggle)
        w('    bool "%s: %s"' % (protocol_of(toggle), kind))
        w("    default IRREMOTE_ENABLE_ALL_PROTOCOLS")
        w("")
    w("endmenu")
    w("")
    w("endmenu")
    w("")
    with open(KCONFIG, "w") as f:
        f.write("\n".join(out))


def write_config_h(toggles, locales):
    out = []
    w = out.append
    w("// Generated by tools/gen_kconfig.py -- do not edit by hand.")
    w("//")
    w("// Translates the Kconfig (menuconfig) selections into the macros the")
    w("// library itself uses. Command line -D flags still win, so an existing")
    w("// PlatformIO/Arduino style build recipe keeps working unchanged.")
    w("")
    w("#ifndef IRCONFIG_H_")
    w("#define IRCONFIG_H_")
    w("")
    w("#ifndef UNIT_TEST")
    w('#include "sdkconfig.h"')
    w("#endif  // UNIT_TEST")
    w("")
    w("#ifdef CONFIG_IRREMOTE_KCONFIG_PRESENT")
    w("")
    w("#if defined(CONFIG_IRREMOTE_DEBUG) && !defined(DEBUG)")
    w("#define DEBUG 1")
    w("#endif")
    w("")
    w("#ifndef _IR_LOCALE_")
    for tag in locales:
        sym = tag.upper().replace("-", "_")
        w("#ifdef CONFIG_IRREMOTE_LOCALE_%s" % sym)
        w("#define _IR_LOCALE_ %s" % tag)
        w("#endif")
    w("#endif  // _IR_LOCALE_")
    w("")
    for toggle in toggles:
        w("#ifndef %s" % toggle)
        w("#ifdef CONFIG_IRREMOTE_%s" % toggle)
        w("#define %s true" % toggle)
        w("#else")
        w("#define %s false" % toggle)
        w("#endif")
        w("#endif  // %s" % toggle)
    w("")
    w("#endif  // CONFIG_IRREMOTE_KCONFIG_PRESENT")
    w("")
    w("#endif  // IRCONFIG_H_")
    w("")
    with open(CONFIG_H, "w") as f:
        f.write("\n".join(out))


def main():
    toggles = collect_toggles()
    locales = collect_locales()
    if not toggles:
        sys.exit("No protocol toggles found in %s" % HEADER)
    write_kconfig(toggles, locales)
    write_config_h(toggles, locales)
    print("Wrote %d protocol options and %d locales." % (len(toggles),
                                                         len(locales)))


if __name__ == "__main__":
    main()
